### ISSUE TITLE
Muse Sounds Manager V2

### ISSUE THREAD

**Issue by DominicMaas** [thilobillerbeck/muse-sounds-manager-nix#2]
Hey, developer of Muse Sounds Manager here,

As a heads up, we've released v2 of Muse Sounds Manager, not too many changes, but we're going to provide a .tar.gz which contains a bin folder for the actual executable + required libraries alongside a .desktop file and the icon resources.

This would probably be preferable to repacking the rpm as the tar.gz version has the built in updater disabled.

This update has not yet been pushed out to the automatic updater for deb and rpm versions. I would consider this an RC build until we get some feedback / ensure there are no major issues.

Here's the current structure of the tar.gz:

```
muse_sounds_manager_x64_2.0.0.0/
muse_sounds_manager_x64_2.0.0.0/README.txt
muse_sounds_manager_x64_2.0.0.0/res/
muse_sounds_manager_x64_2.0.0.0/res/muse-sounds-manager.desktop
muse_sounds_manager_x64_2.0.0.0/res/icons/
muse_sounds_manager_x64_2.0.0.0/res/icons/hicolor/
muse_sounds_manager_x64_2.0.0.0/res/icons/hicolor/128x128/
muse_sounds_manager_x64_2.0.0.0/res/icons/hicolor/128x128/apps/
muse_sounds_manager_x64_2.0.0.0/res/icons/hicolor/128x128/apps/muse-sounds-manager.png
muse_sounds_manager_x64_2.0.0.0/res/icons/hicolor/48x48/
muse_sounds_manager_x64_2.0.0.0/res/icons/hicolor/48x48/apps/
muse_sounds_manager_x64_2.0.0.0/res/icons/hicolor/48x48/apps/muse-sounds-manager.png
muse_sounds_manager_x64_2.0.0.0/res/icons/hicolor/64x64/
muse_sounds_manager_x64_2.0.0.0/res/icons/hicolor/64x64/apps/
muse_sounds_manager_x64_2.0.0.0/res/icons/hicolor/64x64/apps/muse-sounds-manager.png
muse_sounds_manager_x64_2.0.0.0/res/icons/hicolor/256x256/
muse_sounds_manager_x64_2.0.0.0/res/icons/hicolor/256x256/apps/
muse_sounds_manager_x64_2.0.0.0/res/icons/hicolor/256x256/apps/muse-sounds-manager.png
muse_sounds_manager_x64_2.0.0.0/bin/
muse_sounds_manager_x64_2.0.0.0/bin/libSkiaSharp.so
muse_sounds_manager_x64_2.0.0.0/bin/muse-sounds-manager
muse_sounds_manager_x64_2.0.0.0/bin/libServiceCore.so
muse_sounds_manager_x64_2.0.0.0/bin/libHarfBuzzSharp.so
```

Also if there's anything else you need, or anything that'll make repacking easier, just let me know!

TAR: http://muse-cdn.com/Muse_Sounds_Manager_x64.tar.gz

**Comment by orivej** [comment]
Hi, Dominic! I have packaged muse-sounds-manager for Nixpkgs (https://github.com/NixOS/nixpkgs/pull/341856 , the issues stated in the description have already been resolved).

Thank you for the heads up! I'm going to start using this .tar.gz: https://github.com/NixOS/nixpkgs/pull/363378

However, I have encountered a few issues:

1. [important] GUI colors seem off:
![muse-sounds-manager](https://github.com/user-attachments/assets/535d1074-58a5-40de-920a-db38d9880722)
The old version looks fine:
![muse-sounds-manager-1](https://github.com/user-attachments/assets/9195865a-a80e-4189-9fd7-b695610312ff)

2. [inconvenient] After I launch this version, close it and run the old version, close it and try to run this version again, it does not start with the following error:

```
2024-12-08 21:46:09.4926|WARN|Muse.Client.Linux.Interop.MuseHubDownloader|Cannot delete /home/uj/.muse-sounds-manager/downloads as there are unexpected files!
2024-12-08 21:46:09.5626|FATAL|Muse.Client.Linux.App|Application has encountered a fatal exception!|System.IO.IOException: Directory not empty : '/home/uj/.muse-sounds-manager'
   at System.IO.FileSystem.RemoveEmptyDirectory(String fullPath, Boolean topLevel, Boolean throwWhenNotEmpty)
   at System.IO.Directory.Delete(String path)
   at Muse.Client.Linux.Helpers.PathHelpers.DeleteOldDataDirectoriesIfEmpty(ILogger logger) in /home/runner/work/Muse/Muse/Linux/src/Muse.Client.Linux/Helpers/PathHelpers.cs:line 120
   at Muse.Client.Linux.Interop.MuseHubDownloader.Init() in /home/runner/work/Muse/Muse/Linux/src/Muse.Client.Linux/Interop/MuseHubDownloader.cs:line 661
   at Muse.Client.Linux.App.InitCoreAsync() in /home/runner/work/Muse/Muse/Linux/src/Muse.Client.Linux/App.axaml.cs:line 257
   at Muse.Client.Linux.App.OnFrameworkInitializationCompleted() in /home/runner/work/Muse/Muse/Linux/src/Muse.Client.Linux/App.axaml.cs:line 109
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.X11.X11PlatformThreading.CheckSignaled()
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, Action`1 lifetimeBuilder)
   at Muse.Client.Linux.Program.Main(String[] args) in /home/runner/work/Muse/Muse/Linux/src/Muse.Client.Linux/Program.cs:line 19
```

3. [minor] When this version starts, it prints a strange error, but otherwise works:

```
2024-12-08 21:47:30.2704|ERROR|Muse.Client.Linux.Interop.MuseHubLogging|Failed to find any assets in hidden download info query
```

**Comment by orivej** [comment]
> Also if there's anything else you need, or anything that'll make repacking easier, just let me know!

All Linux packages have a difficulty when the upstream URL (in this case http://muse-cdn.com/Muse_Sounds_Manager_x64.tar.gz) points to a resource that changes over time. (Essentially when there is no versioned URL to an immutable archive, such as http://muse-cdn.com/Muse_Sounds_Manager_x64-2.0.3.659.tar.gz) I'll try to explain why is this so.

Consider what happens when a Linux user runs a package manager to update all packages on the system. For each installed package the package manager checks if the installed version is the same as the latest packaged version, and installs the updated package if they are different. How would it check if muse-sounds-manager is out of date? Downloading Muse_Sounds_Manager_x64.tar.gz just to check if it has changed every time a user wants to update their system is not feasible, and is not supported by most package managers, if any. What happens instead is that the package defines not only the URL of the .tar.gz, but also its version, so that the end users could just compare the installed and the packaged version numbers, and install the update when the versions differ. Now, what happens when the .tar.gz at the URL changes? To detect this, package definitions generally include not only the URL and the version, but also the hash sum of the target of the URL. When the target changes, the package fails to be rebuilt with a hash mismatch error.

In some cases (such as Ubuntu PPAs) this bothers only the package maintainers: they have to update the package, while the users can continue installing the latest packaged version. This works because the package ships everything needed inside. In other cases (such as ArchLinux AUR and Nixpkgs of unfree sources) installing a package is running a recipe that downloads it from upstream URL and packages it locally. This recipe breaks whenever the target of the URL changes, and no user can install it until the recipe is updated.

It may be your intention that whenever you ship an update preferably nobody could download and install older versions. If so, please weigh this against the drawback that some of the time (until distributions update their recipes) the new version will not be installable by end users (except by power users willing to do the work themselves). As a compromise, you could make Muse_Sounds_Manager_x64.tar.gz redirect to e.g. Muse_Sounds_Manager_x64-2.0.3.659.tar.gz so that distributions could use the latter URL, while you would keep each version archive available for a month or two. This way the distributions will have the time to update the recipes. The absolute minimum necessary to have the package installable at all times is to keep the current and the previous version (and their URLs must include their version numbers, so that deleted versions would return HTTP 404).

Note that updating recipes by distributions is not a mindless chore. Every update is tested by a package maintainer, and sometimes requires changes besides updating the version and the hash (such as adding dependencies), so it is not expected that a recipe written for one version will just work for all future versions; and distributions generally do not want to pass the burden of checking whether updating only the version and the hash was enough to end users - it requires perhaps a trivial but a manual check, which takes time.

**Comment by DominicMaas** [comment]
1. In terms of the GUI colors, there was some alignment of colors to match branding guidelines, so the color changes are expected.

2. I'll try dig into this error, although an unsupported / untested scenario. 

3. As expected for the TAR version (it's the auto updater looking for a new version)

4. Sounds reasonable, we'll look into a way of exposing version download links. probably with a similar suffix to what you have specified, and the current url will always point towards the latest version.

**Comment by DominicMaas** [comment]
Hey, following up here.

We now have a process for storing fixed versions (see below):

- `https://muse-cdn.com/Muse_Sounds_Manager_x64.tar.gz`
- `https://muse-cdn.com/muse-sounds-manager/Muse_Sounds_Manager_x64_2.0.3.659.tar.gz`
- `https://muse-cdn.com/muse-sounds-manager/Muse_Sounds_Manager_x64_2.0.4.872.tar.gz`

Changelog will eventually end up here. When 2.0.5 releases I'll create a new issue.

https://support.musehub.com/hc/en-gb/categories/29418716667549-MuseSounds-Manager
